import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

import "./globals.css";
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calorie Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <ColorSchemeScript />
        </head>
        <body className={inter.className}>
          <MantineProvider>
            {children}
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
